name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Build with Buildozer
        uses: digreat/buildozer-action@v3
        with:
          buildozer_version: stable
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MV-Player-APK
          path: bin/*.apk
